apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: vector-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: ghcr.io/chroma-core/chroma:latest  # Use official image
        ports:
        - containerPort: 8000
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        volumeMounts:
        - name: chroma-data
          mountPath: /chroma
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: vector-db
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
