apiVersion: v1
kind: LimitRange
metadata:
  name: chromadb-resource-limits
  namespace: vector-db
spec:
  limits:
  - type: Container
    max:
      memory: "2Gi"
      cpu: "1"
    min:
      memory: "512Mi"
      cpu: "250m"
    default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "512Mi"
      cpu: "250m"